# Generated by Django 5.0.6 on 2025-02-07 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_result_studentanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='is_attempted',
            field=models.BooleanField(default=False),
        ),
    ]
