const questions = [
  {
    id: 1,
    question: "What is the time complexity of Merge Sort?",
    options: ["O(n)", "O(n log n)", "O(n²)", "O(log n)"],
    correctAnswer: 1,
  },
  {
    id: 2,
    question: "Which data structure follows FIFO principle?",
    options: ["Queue", "Stack", "Linked List", "Heap"],
    correctAnswer: 0,
  },
  {
    id: 3,
    question: "What is the worst-case time complexity of QuickSort?",
    options: ["O(n)", "O(n log n)", "O(n²)", "O(log n)"],
    correctAnswer: 2,
  },
  {
    id: 4,
    question: "Which data structure is used for recursion?",
    options: ["Queue", "Stack", "Heap", "Array"],
    correctAnswer: 1,
  },
  {
    id: 5,
    question: "What is the space complexity of DFS?",
    options: ["O(V+E)", "O(V)", "O(E)", "O(1)"],
    correctAnswer: 1,
  },
  {
    id: 6,
    question: "Which sorting algorithm is stable?",
    options: ["Merge Sort", "Quick Sort", "Heap Sort", "Selection Sort"],
    correctAnswer: 0,
  },
  {
    id: 7,
    question: "Which data structure is used for priority queues?",
    options: ["Stack", "Queue", "Heap", "Graph"],
    correctAnswer: 2,
  },
  {
    id: 8,
    question: "What does ACID stand for in databases?",
    options: [
      "Atomicity, Consistency, Isolation, Durability",
      "Accuracy, Conciseness, Integrity, Durability",
      "Automation, Consistency, Integrity, Data",
      "Atomicity, Complexity, Isolation, Durability",
    ],
    correctAnswer: 0,
  },
  {
    id: 9,
    question: "What is the time complexity of searching in a balanced BST?",
    options: ["O(1)", "O(log n)", "O(n)", "O(n log n)"],
    correctAnswer: 1,
  },
  {
    id: 10,
    question: "Which of the following is a NoSQL database?",
    options: ["MySQL", "PostgreSQL", "MongoDB", "SQLite"],
    correctAnswer: 2,
  },
  {
    id: 11,
    question: "What is the time complexity of inserting in a heap?",
    options: ["O(1)", "O(log n)", "O(n)", "O(n log n)"],
    correctAnswer: 1,
  },
  {
    id: 12,
    question: "Which of these is a self-balancing binary search tree?",
    options: ["AVL Tree", "Binary Search Tree", "Red-Black Tree", "B Tree"],
    correctAnswer: 0,
  },
  {
    id: 13,
    question: "What is the time complexity of Bubble Sort?",
    options: ["O(n)", "O(n log n)", "O(n²)", "O(log n)"],
    correctAnswer: 2,
  },
  {
    id: 14,
    question: "What does CRUD stand for in databases?",
    options: [
      "Create, Read, Update, Delete",
      "Compile, Run, Update, Delete",
      "Create, Run, Update, Define",
      "Create, Retrieve, Update, Delete",
    ],
    correctAnswer: 0,
  },
  {
    id: 15,
    question: "Which of the following is a graph traversal algorithm?",
    options: ["DFS", "Binary Search", "QuickSort", "MergeSort"],
    correctAnswer: 0,
  },
  {
    id: 16,
    question: "What is the space complexity of Breadth-First Search?",
    options: ["O(V+E)", "O(V)", "O(E)", "O(1)"],
    correctAnswer: 1,
  },
  {
    id: 17,
    question: "Which of the following is a key-value store database?",
    options: ["MySQL", "PostgreSQL", "Redis", "SQLite"],
    correctAnswer: 2,
  },
  {
    id: 18,
    question:
      "What is the time complexity of Dijkstra's algorithm using a priority queue?",
    options: ["O(V^2)", "O(V + E log V)", "O(V log V + E)", "O(E log V)"],
    correctAnswer: 1,
  },
  {
    id: 19,
    question: "Which sorting algorithm uses the divide-and-conquer approach?",
    options: ["Merge Sort", "Selection Sort", "Bubble Sort", "Insertion Sort"],
    correctAnswer: 0,
  },
  {
    id: 20,
    question: "What does ACID stand for in the context of databases?",
    options: [
      "Accuracy, Consistency, Integrity, Durability",
      "Automation, Consistency, Isolation, Durability",
      "Atomicity, Consistency, Isolation, Durability",
      "Atomicity, Complexity, Integrity, Data",
    ],
    correctAnswer: 2,
  },
  {
    id: 21,
    question: "Which of the following is a schema-less database?",
    options: ["MySQL", "PostgreSQL", "MongoDB", "Oracle"],
    correctAnswer: 2,
  },
  {
    id: 22,
    question: "What is the worst-case time complexity of binary search?",
    options: ["O(1)", "O(n)", "O(n log n)", "O(log n)"],
    correctAnswer: 3,
  },
  {
    id: 23,
    question: "Which of the following is a NoSQL database?",
    options: ["Oracle", "Cassandra", "SQLite", "MySQL"],
    correctAnswer: 1,
  },
  {
    id: 24,
    question:
      "What is the time complexity of deleting a node from a binary search tree?",
    options: ["O(1)", "O(n)", "O(n log n)", "O(log n)"],
    correctAnswer: 3,
  },
  {
    id: 25,
    question: "Which of the following sorting algorithms is in-place?",
    options: ["Merge Sort", "Heap Sort", "Counting Sort", "Radix Sort"],
    correctAnswer: 1,
  },
  {
    id: 26,
    question: "What is the primary difference between a Stack and a Queue?",
    options: [
      "FIFO vs LIFO",
      "LIFO vs FIFO",
      "Stack uses an array while Queue uses a linked list",
      "Queue is faster than Stack",
    ],
    correctAnswer: 1,
  },
  {
    id: 27,
    question: "Which of the following is a graph traversal algorithm?",
    options: ["DFS", "Binary Search", "QuickSort", "MergeSort"],
    correctAnswer: 0,
  },
  {
    id: 28,
    question: "What is the space complexity of Depth-First Search?",
    options: ["O(V+E)", "O(V)", "O(E)", "O(1)"],
    correctAnswer: 1,
  },
  {
    id: 29,
    question: "Which of the following is a key-value store database?",
    options: ["MySQL", "PostgreSQL", "Redis", "SQLite"],
    correctAnswer: 2,
  },
  {
    id: 30,
    question:
      "What is the time complexity of Dijkstra's algorithm using a priority queue?",
    options: ["O(V^2)", "O(V + E log V)", "O(V log V + E)", "O(E log V)"],
    correctAnswer: 1,
  },
  {
    id: 31,
    question: "Which sorting algorithm uses the divide-and-conquer approach?",
    options: ["Merge Sort", "Selection Sort", "Bubble Sort", "Insertion Sort"],
    correctAnswer: 0,
  },
  {
    id: 32,
    question: "What does ACID stand for in the context of databases?",
    options: [
      "Accuracy, Consistency, Integrity, Durability",
      "Automation, Consistency, Isolation, Durability",
      "Atomicity, Consistency, Isolation, Durability",
      "Atomicity, Complexity, Integrity, Data",
    ],
    correctAnswer: 2,
  },
  {
    id: 33,
    question: "Which of the following is a schema-less database?",
    options: ["MySQL", "PostgreSQL", "MongoDB", "Oracle"],
    correctAnswer: 2,
  },
  {
    id: 34,
    question: "What is the worst-case time complexity of binary search?",
    options: ["O(1)", "O(n)", "O(n log n)", "O(log n)"],
    correctAnswer: 3,
  },
  {
    id: 35,
    question: "Which of the following is a NoSQL database?",
    options: ["Oracle", "Cassandra", "SQLite", "MySQL"],
    correctAnswer: 1,
  },
  {
    id: 36,
    question:
      "What is the time complexity of deleting a node from a binary search tree?",
    options: ["O(1)", "O(n)", "O(n log n)", "O(log n)"],
    correctAnswer: 3,
  },
  {
    id: 37,
    question: "Which of the following sorting algorithms is in-place?",
    options: ["Merge Sort", "Heap Sort", "Counting Sort", "Radix Sort"],
    correctAnswer: 1,
  },
  {
    id: 38,
    question: "What is the primary difference between a Stack and a Queue?",
    options: [
      "FIFO vs LIFO",
      "LIFO vs FIFO",
      "Stack uses an array while Queue uses a linked list",
      "Queue is faster than Stack",
    ],
    correctAnswer: 1,
  },
  {
    id: 39,
    question: "Which of the following is a graph traversal algorithm?",
    options: ["DFS", "Binary Search", "QuickSort", "MergeSort"],
    correctAnswer: 0,
  },
  {
    id: 40,
    question: "What is the space complexity of Depth-First Search?",
    options: ["O(V+E)", "O(V)", "O(E)", "O(1)"],
    correctAnswer: 1,
  },
  {
    id: 41,
    question: "Which of the following is a key-value store database?",
    options: ["MySQL", "PostgreSQL", "Redis", "SQLite"],
    correctAnswer: 2,
  },
  {
    id: 42,
    question:
      "What is the time complexity of Dijkstra's algorithm using a priority queue?",
    options: ["O(V^2)", "O(V + E log V)", "O(V log V + E)", "O(E log V)"],
    correctAnswer: 1,
  },
  {
    id: 43,
    question: "Which sorting algorithm uses the divide-and-conquer approach?",
    options: ["Merge Sort", "Selection Sort", "Bubble Sort", "Insertion Sort"],
    correctAnswer: 0,
  },
  {
    id: 44,
    question: "What does ACID stand for in the context of databases?",
    options: [
      "Accuracy, Consistency, Integrity, Durability",
      "Automation, Consistency, Isolation, Durability",
      "Atomicity, Consistency, Isolation, Durability",
      "Atomicity, Complexity, Integrity, Data",
    ],
    correctAnswer: 2,
  },
  {
    id: 45,
    question: "Which of the following is a schema-less database?",
    options: ["MySQL", "PostgreSQL", "MongoDB", "Oracle"],
    correctAnswer: 2,
  },
  {
    id: 46,
    question: "What is the worst-case time complexity of binary search?",
    options: ["O(1)", "O(n)", "O(n log n)", "O(log n)"],
    correctAnswer: 3,
  },
  {
    id: 47,
    question: "Which of the following is a NoSQL database?",
    options: ["Oracle", "Cassandra", "SQLite", "MySQL"],
    correctAnswer: 1,
  },
  {
    id: 48,
    question:
      "What is the time complexity of deleting a node from a binary search tree?",
    options: ["O(1)", "O(n)", "O(n log n)", "O(log n)"],
    correctAnswer: 3,
  },
  {
    id: 49,
    question: "Which of the following sorting algorithms is in-place?",
    options: ["Merge Sort", "Heap Sort", "Counting Sort", "Radix Sort"],
    correctAnswer: 1,
  },
  {
    id: 50,
    question: "What is the primary difference between a Stack and a Queue?",
    options: [
      "FIFO vs LIFO",
      "LIFO vs FIFO",
      "Stack uses an array while Queue uses a linked list",
      "Queue is faster than Stack",
    ],
    correctAnswer: 1,
  },
  {
    id: 51,
    question:
      "What is the time complexity of accessing an element in an array?",
    options: ["O(1)", "O(log n)", "O(n)", "O(n log n)"],
    correctAnswer: 0,
  },
  {
    id: 52,
    question: "Which of these is a balanced search tree?",
    options: ["Binary Tree", "AVL Tree", "Binary Search Tree", "Heap"],
    correctAnswer: 1,
  },
  {
    id: 53,
    question: "What is the time complexity of Insertion Sort?",
    options: ["O(n)", "O(n log n)", "O(n²)", "O(log n)"],
    correctAnswer: 2,
  },
  {
    id: 54,
    question: "What does REST stand for?",
    options: [
      "Representational State Transfer",
      "Remote Execution of State",
      "Representational Stack Transfer",
      "Remote State Transfer",
    ],
    correctAnswer: 0,
  },
  {
    id: 55,
    question: "Which of the following is a graph representation?",
    options: ["Adjacency Matrix", "Binary Heap", "Stack", "Queue"],
    correctAnswer: 0,
  },
  {
    id: 56,
    question: "What is the space complexity of a Hash Map?",
    options: ["O(1)", "O(log n)", "O(n)", "O(n²)"],
    correctAnswer: 2,
  },
  {
    id: 57,
    question: "Which of the following is a document-oriented database?",
    options: ["MySQL", "PostgreSQL", "MongoDB", "SQLite"],
    correctAnswer: 2,
  },
  {
    id: 58,
    question: "What is the time complexity of Floyd-Warshall algorithm?",
    options: ["O(n)", "O(n³)", "O(n²)", "O(n log n)"],
    correctAnswer: 1,
  },
  {
    id: 59,
    question: "Which sorting algorithm is not stable?",
    options: ["Merge Sort", "Bubble Sort", "Insertion Sort", "Quick Sort"],
    correctAnswer: 3,
  },
  {
    id: 60,
    question: "What does CAP theorem stand for?",
    options: [
      "Consistency, Availability, Partition Tolerance",
      "Consistency, Accuracy, Partition Tolerance",
      "Consistency, Availability, Performance",
      "Consistency, Availability, Partition",
    ],
    correctAnswer: 0,
  },
  {
    id: 61,
    question: "Which of the following is an in-memory database?",
    options: ["MySQL", "PostgreSQL", "Redis", "SQLite"],
    correctAnswer: 2,
  },
  {
    id: 62,
    question: "What is the time complexity of linear search?",
    options: ["O(1)", "O(log n)", "O(n)", "O(n log n)"],
    correctAnswer: 2,
  },
  {
    id: 63,
    question: "Which data structure is used for implementing LRU cache?",
    options: ["Array", "Stack", "Queue", "Linked List"],
    correctAnswer: 3,
  },
  {
    id: 64,
    question: "What is the space complexity of Kruskal's algorithm?",
    options: ["O(V+E)", "O(V)", "O(E)", "O(1)"],
    correctAnswer: 0,
  },
  {
    id: 65,
    question: "Which of the following is a key-value database?",
    options: ["MySQL", "PostgreSQL", "MongoDB", "Cassandra"],
    correctAnswer: 3,
  },
  {
    id: 66,
    question: "What is the time complexity of Bellman-Ford algorithm?",
    options: ["O(V)", "O(V²)", "O(VE)", "O(E²)"],
    correctAnswer: 2,
  },
  {
    id: 67,
    question: "Which of these is not a self-balancing tree?",
    options: ["AVL Tree", "Red-Black Tree", "Binary Search Tree", "B Tree"],
    correctAnswer: 2,
  },
  {
    id: 68,
    question: "What does BASE stand for in NoSQL databases?",
    options: [
      "Basically Available, Soft state, Eventually consistent",
      "Basic Availability, Scalable, Efficient",
      "Basic Access, Soft state, Eventually consistent",
      "Basically Available, Soft state, Efficient",
    ],
    correctAnswer: 0,
  },
  {
    id: 69,
    question: "Which of the following uses trie data structure?",
    options: [
      "Spell checker",
      "Sorting algorithm",
      "Graph traversal",
      "Database indexing",
    ],
    correctAnswer: 0,
  },
  {
    id: 70,
    question:
      "What is the time complexity of Prim's algorithm using adjacency matrix?",
    options: ["O(V²)", "O(V + E log V)", "O(V log V + E)", "O(E log V)"],
    correctAnswer: 0,
  },
  {
    id: 71,
    question: "Which sorting algorithm is not in-place?",
    options: ["Heap Sort", "Quick Sort", "Merge Sort", "Insertion Sort"],
    correctAnswer: 2,
  },
  {
    id: 72,
    question: "What is the space complexity of Dijkstra's algorithm?",
    options: ["O(V²)", "O(V + E)", "O(V log V)", "O(E log V)"],
    correctAnswer: 1,
  },
  {
    id: 73,
    question: "Which of these data structures is used for implementing BFS?",
    options: ["Stack", "Queue", "Heap", "Tree"],
    correctAnswer: 1,
  },
  {
    id: 74,
    question: "What is the time complexity of Heap Sort?",
    options: ["O(n)", "O(n log n)", "O(n²)", "O(log n)"],
    correctAnswer: 1,
  },
  {
    id: 75,
    question: "Which of the following is a column-family database?",
    options: ["MySQL", "PostgreSQL", "MongoDB", "Cassandra"],
    correctAnswer: 3,
  },
  {
    id: 76,
    question: "What is the space complexity of Radix Sort?",
    options: ["O(n)", "O(n log n)", "O(n²)", "O(n + k)"],
    correctAnswer: 3,
  },
  {
    id: 77,
    question: "Which data structure is used for implementing DFS?",
    options: ["Stack", "Queue", "Heap", "Tree"],
    correctAnswer: 0,
  },
  {
    id: 78,
    question: "What is the time complexity of binary search?",
    options: ["O(1)", "O(log n)", "O(n)", "O(n log n)"],
    correctAnswer: 1,
  },
  {
    id: 79,
    question: "Which sorting algorithm is considered the fastest on average?",
    options: ["Merge Sort", "Quick Sort", "Heap Sort", "Bubble Sort"],
    correctAnswer: 1,
  },
  {
    id: 80,
    question: "What does SQL stand for?",
    options: [
      "Structured Query Language",
      "Simple Query Language",
      "Standard Query Language",
      "Sequential Query Language",
    ],
    correctAnswer: 0,
  },
  {
    id: 81,
    question: "Which of these is an attribute of a binary search tree?",
    options: [
      "Every node has two children",
      "Nodes are sorted",
      "Nodes can have only one child",
      "All nodes are equal",
    ],
    correctAnswer: 1,
  },
  {
    id: 82,
    question: "What is the time complexity of inserting in an AVL tree?",
    options: ["O(1)", "O(log n)", "O(n)", "O(n log n)"],
    correctAnswer: 1,
  },
  {
    id: 83,
    question: "Which sorting algorithm is best for nearly sorted arrays?",
    options: ["Bubble Sort", "Insertion Sort", "Selection Sort", "Heap Sort"],
    correctAnswer: 1,
  },
  {
    id: 84,
    question: "What does OLAP stand for?",
    options: [
      "Online Analytical Processing",
      "Online Algorithmic Processing",
      "Offline Analytical Processing",
      "Online Analysis Processing",
    ],
    correctAnswer: 0,
  },
  {
    id: 85,
    question: "Which of these is not a NoSQL database?",
    options: ["MySQL", "MongoDB", "Cassandra", "CouchDB"],
    correctAnswer: 0,
  },
  {
    id: 86,
    question: "What is the space complexity of Heap Sort?",
    options: ["O(1)", "O(log n)", "O(n)", "O(n log n)"],
    correctAnswer: 2,
  },
  {
    id: 87,
    question: "Which of these is a graph search algorithm?",
    options: ["DFS", "Binary Search", "Merge Sort", "Selection Sort"],
    correctAnswer: 0,
  },
  {
    id: 88,
    question: "What is the time complexity of Quick Sort in the average case?",
    options: ["O(n)", "O(log n)", "O(n²)", "O(n log n)"],
    correctAnswer: 3,
  },
  {
    id: 89,
    question: "Which data structure is used for implementing priority queues?",
    options: ["Stack", "Queue", "Heap", "Linked List"],
    correctAnswer: 2,
  },
  {
    id: 90,
    question: "What does OLTP stand for?",
    options: [
      "Online Transaction Processing",
      "Online Transfer Processing",
      "Offline Transaction Processing",
      "Online Temporary Processing",
    ],
    correctAnswer: 0,
  },
  {
    id: 91,
    question: "Which of these is an example of a key-value database?",
    options: ["MySQL", "PostgreSQL", "Redis", "Oracle"],
    correctAnswer: 2,
  },
  {
    id: 92,
    question:
      "What is the time complexity of selecting the minimum element in a binary heap?",
    options: ["O(1)", "O(log n)", "O(n)", "O(n log n)"],
    correctAnswer: 0,
  },
];

export default questions;